cachecloud-open-web/src/main/java/com/sohu/cache/entity/AppDesc.java
package com.sohu.cache.entity;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;

import com.sohu.cache.constant.AppStatusEnum;
import com.sohu.cache.util.ConstUtils;

/**
 * 应用的信息，包括分片、类型以及各分片的ip
 * <p/>
 * User: lingguo
 * Date: 14-5-29
 * Time: 下午9:42
 */
public class AppDesc implements Serializable {
    private static final long serialVersionUID = -3507970915810652761L;

    /**
     * 应用id
     */
    private long appId;

    /**
     * 应用名称
     */
    private String name;

    /**
     * 用户id
     */
    private long userId;

    /**
     * 应用状态, 0未分配，1是申请了未审批，2是审批并发布, 3应用下线
     */
    private int status;

    /**
     * 应用描述
     */
    private String intro;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 申请通过的时间
     */
    private Date passedTime;

    /**
     * 类型
     */
    private int type;

    /**
     * 类型描述
     */
    private String typeDesc;

    /**
     * 负责人
     */
    private String officer;

    /**
     * 版本号
     */
    private int verId;

    /**
     * 是否测试：1是0否
     */
    private int isTest;

    /**
     * 是否有后端数据源: 1是0否
     */
    private int hasBackStore;

    /**
     * 是否需要持久化: 1是0否
     */
    private int needPersistence;

    /**
     * 预估qps
     */
    private int forecaseQps;

    /**
     * 是否需要热备: 1是0否
     */
    private int needHotBackUp;

    /**
     * 预估条目数
     */
    private int forecastObjNum;

    /**
     * 内存报警阀值
     */
    private int memAlertValue;
    
    /**
     * 客户端机器机房
     */
    private String clientMachineRoom;

    public long getAppId() {
        return appId;
    }

    public void setAppId(long appId) {
        this.appId = appId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public String getIntro() {
        return intro;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getPassedTime() {
        return passedTime;
    }

    public void setPassedTime(Date passedTime) {
        this.passedTime = passedTime;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getOfficer() {
        return officer;
    }

    public void setOfficer(String officer) {
        this.officer = officer;
    }

    public int getVerId() {
        return verId;
    }

    public void setVerId(int verId) {
        this.verId = verId;
    }

    public int getIsTest() {
        return isTest;
    }

    public void setIsTest(int isTest) {
        this.isTest = isTest;
    }

    public int getHasBackStore() {
        return hasBackStore;
    }

    public void setHasBackStore(int hasBackStore) {
        this.hasBackStore = hasBackStore;
    }

    public int getNeedPersistence() {
        return needPersistence;
    }

    public void setNeedPersistence(int needPersistence) {
        this.needPersistence = needPersistence;
    }


    public int getForecaseQps() {
        return forecaseQps;
    }

    public void setForecaseQps(int forecaseQps) {
        this.forecaseQps = forecaseQps;
    }

    public int getNeedHotBackUp() {
        return needHotBackUp;
    }

    public void setNeedHotBackUp(int needHotBackUp) {
        this.needHotBackUp = needHotBackUp;
    }

    public int getForecastObjNum() {
        return forecastObjNum;
    }

    public void setForecastObjNum(int forecastObjNum) {
        this.forecastObjNum = forecastObjNum;
    }

    public int getMemAlertValue() {
        return memAlertValue;
    }

    public void setMemAlertValue(int memAlertValue) {
        this.memAlertValue = memAlertValue;
    }

    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc;
    }

    public String getClientMachineRoom() {
        return clientMachineRoom;
    }

    public void setClientMachineRoom(String clientMachineRoom) {
        this.clientMachineRoom = clientMachineRoom;
    }

    /**
     * 应用运行天数
     */
    public int getAppRunDays() {
        if (createTime == null) {
            return -1;
        }
        Date now = new Date();
        long diff = now.getTime() - createTime.getTime();
        return (int) (diff / TimeUnit.DAYS.toMillis(1));
    }

    public String getTypeDesc() {
        if (type <= 0) {
            return "";
        } else if (type == ConstUtils.CACHE_TYPE_REDIS_CLUSTER) {
            return "redis-cluster";
        } else if (type == ConstUtils.CACHE_REDIS_SENTINEL) {
            return "redis-sentinel";
        } else if (type == ConstUtils.CACHE_REDIS_STANDALONE) {
            return "redis-standalone";
        }
        return "";
    }
    
    public String getCreateTimeFormat(){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        if(createTime != null){
            return sdf.format(createTime);
        }
        return "";
    }

    @Override
    public String toString() {
        return "AppDesc [appId=" + appId + ", name=" + name + ", userId=" + userId + ", status=" + status + ", intro="
                + intro + ", createTime=" + createTime + ", passedTime=" + passedTime + ", type=" + type
                + ", typeDesc=" + typeDesc + ", officer=" + officer + ", verId=" + verId + ", isTest=" + isTest
                + ", hasBackStore=" + hasBackStore + ", needPersistence=" + needPersistence + ", forecaseQps="
                + forecaseQps + ", needHotBackUp=" + needHotBackUp + ", forecastObjNum=" + forecastObjNum
                + ", memAlertValue=" + memAlertValue + ", clientMachineRoom=" + clientMachineRoom + "]";
    }

    public String getStatusDesc() {
        AppStatusEnum appStatusEnum = AppStatusEnum.getByStatus(status);
        if (appStatusEnum != null) {
            return appStatusEnum.getInfo();
        }
        return "";
    }

}

cachecloud-open-web/src/main/java/com/sohu/cache/entity/AppStats.java
package com.sohu.cache.entity;

import java.util.Date;
import java.util.List;

/**
 * Created by yijunzhang on 14-6-9.
 */
public class AppStats {

    /**
     * 应用id
     */
    private long appId;

    /**
     * 收集时间:格式yyyyMMddHHmm/yyyyMMdd/yyyyMMddHH
     */
    private long collectTime;

    /**
     * 命中数量
     */
    private long hits;

    /**
     * 未命中数量
     */
    private long misses;

    /**
     * 命令执行次数
     */
    private long commandCount;

    /**
     * 内存占用
     */
    private long usedMemory;

    /**
     * 过期key数量
     */
    private long expiredKeys;

    /**
     * 驱逐key数量
     */
    private long evictedKeys;

    /**
     * 网络输入字节
     */
    private long netInputByte;

    /**
     * 网络输出字节
     */
    private long netOutputByte;

    /**
     * 客户端连接数
     */
    private int connectedClients;

    /**
     * 存储对象数
     */
    private long objectSize;

    /**
     * 累加的实例数
     */
    private int accumulation;

    /**
     * 创建时间
     */
    private Date createTime;
    /**
     * 修改时间
     */
    private Date modifyTime;

    /**
     * 命令统计集合
     */
    private List<AppCommandStats> commandStatsList;

    public long getAppId() {
        return appId;
    }

    public void setAppId(long appId) {
        this.appId = appId;
    }

    public long getCollectTime() {
        return collectTime;
    }

    public void setCollectTime(long collectTime) {
        this.collectTime = collectTime;
    }

    public long getHits() {
        return hits;
    }

    public void setHits(long hits) {
        this.hits = hits;
    }

    public long getMisses() {
        return misses;
    }

    public void setMisses(long misses) {
        this.misses = misses;
    }

    public long getUsedMemory() {
        return usedMemory;
    }

    public void setUsedMemory(long usedMemory) {
        this.usedMemory = usedMemory;
    }

    public long getExpiredKeys() {
        return expiredKeys;
    }

    public void setExpiredKeys(long expiredKeys) {
        this.expiredKeys = expiredKeys;
    }

    public long getEvictedKeys() {
        return evictedKeys;
    }

    public void setEvictedKeys(long evictedKeys) {
        this.evictedKeys = evictedKeys;
    }

    public int getConnectedClients() {
        return connectedClients;
    }

    public void setConnectedClients(int connectedClients) {
        this.connectedClients = connectedClients;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Override
    public String toString() {
        return "AppStats{" +
                "appId=" + appId +
                ", collectTime=" + collectTime +
                ", hits=" + hits +
                ", misses=" + misses +
                ", usedMemory=" + usedMemory +
                ", expiredKeys=" + expiredKeys +
                ", evictedKeys=" + evictedKeys +
                ", connectedClients=" + connectedClients +
                ", createTime=" + createTime +
                ", modifyTime=" + modifyTime +
                ", objectSize=" + objectSize +
                ", accumulation=" + accumulation +
                '}';
    }

    public long getCommandCount() {
        return commandCount;
    }

    public void setCommandCount(long commandCount) {
        this.commandCount = commandCount;
    }

    public void setObjectSize(long objectSize) {
        this.objectSize = objectSize;
    }

    public long getObjectSize() {
        return objectSize;
    }

    public int getAccumulation() {
        return accumulation;
    }

    public void setAccumulation(int accumulation) {
        this.accumulation = accumulation;
    }

    public List<AppCommandStats> getCommandStatsList() {
        return commandStatsList;
    }

    public void setCommandStatsList(List<AppCommandStats> commandStatsList) {
        this.commandStatsList = commandStatsList;
    }

    public long getNetInputByte() {
        return netInputByte;
    }

    public void setNetInputByte(long netInputByte) {
        this.netInputByte = netInputByte;
    }

    public long getNetOutputByte() {
        return netOutputByte;
    }

    public void setNetOutputByte(long netOutputByte) {
        this.netOutputByte = netOutputByte;
    }
}

cachecloud-open-web/src/main/java/com/sohu/cache/entity/InstanceStats.java
package com.sohu.cache.entity;

import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.util.Map;

/**
 * 实例的简化的统计信息
 *
 * User: lingguo
 * Date: 14-7-27 下午3:59
 */
public class InstanceStats {
    /* id */
    private long id;

    /* 实例id */
    private long instId;

    /* app id */
    private long appId;

    /* host id */
    private long hostId;

    /* ip地址 */
    private String ip;

    /* port */
    private int port;

    /* 主从，1主2从 */
    private byte role;

    /* 启用实例时设置的内存，单位：byte */
    private long maxMemory;

    /* 实例当前已用的内存，单位：byte */
    private long usedMemory;

    /*
     * 实例内存使用率
     */
    private double memUsePercent;

    /* 当前的item数 */
    private long currItems;

    /* 当前的连接数 */
    private int currConnections;

    /* 未命中数*/
    private long misses;

    /* 命中数 */
    private long hits;

    /* 开始收集时间 */
    private Timestamp createTime;

    /* 最后更新时间 */
    private Timestamp modifyTime;

    private boolean isRun;

    /**
     * 实例相关全部统计指标
     */
    private Map<String,Object> infoMap;

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public int getPort() {
        return port;
    }

    public void setPort(int port) {
        this.port = port;
    }

    public long getMaxMemory() {
        return maxMemory;
    }

    public void setMaxMemory(long maxMemory) {
        this.maxMemory = maxMemory;
    }

    public long getUsedMemory() {
        return usedMemory;
    }

    public void setUsedMemory(long usedMemory) {
        this.usedMemory = usedMemory;
    }

    public long getCurrItems() {
        return currItems;
    }

    public void setCurrItems(long currItems) {
        this.currItems = currItems;
    }

    public int getCurrConnections() {
        return currConnections;
    }

    public void setCurrConnections(int currConnections) {
        this.currConnections = currConnections;
    }


    public long getMisses() {
        return misses;
    }

    public void setMisses(long misses) {
        this.misses = misses;
    }

    public long getHits() {
        return hits;
    }

    public void setHits(long hits) {
        this.hits = hits;
    }

    public long getAppId() {
        return appId;
    }

    public void setAppId(long appId) {
        this.appId = appId;
    }

    public long getHostId() {
        return hostId;
    }

    public void setHostId(long hostId) {
        this.hostId = hostId;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Timestamp getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Timestamp modifyTime) {
        this.modifyTime = modifyTime;
    }

    public byte getRole() {
        return role;
    }

    public void setRole(byte role) {
        this.role = role;
    }

    public long getInstId() {
        return instId;
    }

    public void setInstId(long instId) {
        this.instId = instId;
    }

    @Override
    public String toString() {
        return "InstanceStats{" +
                "id=" + id +
                ", instId=" + instId +
                ", appId=" + appId +
                ", hostId=" + hostId +
                ", ip='" + ip + '\'' +
                ", port=" + port +
                ", role=" + role +
                ", maxMemory=" + maxMemory +
                ", usedMemory=" + usedMemory +
                ", currItems=" + currItems +
                ", currConnections=" + currConnections +
                ", misses=" + misses +
                ", hits=" + hits +
                ", createTime=" + createTime +
                ", modifyTime=" + modifyTime +
                '}';
    }

    public Map<String, Object> getInfoMap() {
        return infoMap;
    }

    public void setInfoMap(Map<String, Object> infoMap) {
        this.infoMap = infoMap;
    }

    public boolean isRun() {
        return isRun;
    }

    public void setRun(boolean isRun) {
        this.isRun = isRun;
    }

    public double getMemUsePercent() {
        if(maxMemory<=0){
            return 0.0D;
        }
        double percent = 100 * (double) usedMemory / (maxMemory);
        DecimalFormat df = new DecimalFormat("##.##");
        return Double.parseDouble(df.format(percent));
    }
    
    /**
     * 命中率
     * @return
     */
    public String getHitPercent(){
		long totalHits = hits + misses;
		if (totalHits <= 0) {
			return "无命令执行";
		}
		double percent = 100 * (double) hits / totalHits;
		DecimalFormat df = new DecimalFormat("##.##");
		return df.format(percent) + "%";
    }
}

cachecloud-open-web/src/main/webapp/WEB-INF/jsp/app/appCommand.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<div class="row">
    <div id="console" class="console"></div>
    <script type="text/javascript">
        $(document).ready(function () {
            var console = $('#console');
            var controller = console.console({
                promptLabel: 'appId:${appId}> ',
                commandValidate: function (line) {
                    if (line == "") return false;
                    else return true;
                },
                commandHandle: function (line,report) {
                    $.ajax({
                        url: "/admin/app/commandExecute.json",
                        data: {appId: $('#appId').val(), command: line},
                        dataType: "json",
                        success: function (result) {
                            report([
                                {msg: result.result,
                                    className: "jquery-console-message-value"}
                            ]);
                        }
                    });
                },
                autofocus: true,
                animateScroll: true,
                promptHistory: true
            });
        });
    </script>
    <center><h4><font color='red'>注意：非测试应用只可以执行只读命令，如有需要清理数据请联系管理员！</font></h4></center>

    <input type="hidden" id="appId" value="${appId}">

</div>

cachecloud-open-web/src/main/webapp/WEB-INF/jsp/app/appCommandAnalysis.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java"%>
<%@ include file="/WEB-INF/jsp/manage/commons/taglibs.jsp"%>

<script type="text/javascript">
var firstCommand = '${firstCommand}';
var startDate = '${startDate}';
var endDate = '${endDate}';
var yesterDate = '${yesterDay}';
var betweenOneDay = '${betweenOneDay}';
var appId = '${appId}'; 
var chartParams = "&startDate="+startDate+"&endDate="+endDate;
var chartParamsCompare = "&startDate="+yesterDate+"&endDate="+startDate;
Highcharts.setOptions({
	global : {
		useUTC : false
	}
});
Highcharts.setOptions({
	colors : ['#2f7ed8', '#E3170D', '#0d233a', '#8bbc21', '#1aadce',
			'#492970', '#804000', '#f28f43', '#77a1e5',
			'#c42525', '#a6c96a']
});

function changeCommandChart(value){
	document.getElementById("firstCommand").value = value;
	document.getElementById("formSingCommand").submit();
}
</script>

<div class="container">
	<br/>
	<form method="post" action="/admin/app/index.do" id="formSingCommand">
		<div class="row">
			<div style="float:right">
					<label style="font-weight:bold;text-align:left;">
					 	开始日期:&nbsp;&nbsp;
					</label>
					<input type="text" size="21" name="startDate" id="startDate" value="${startDate}" onFocus="WdatePicker({startDate:'%y-%M-01',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true})"/>
					<label style="font-weight:bold;text-align:left;">
					 	结束日期:
					</label>
					<input type="text" size="20" name="endDate" id="endDate" value="${endDate}" onFocus="WdatePicker({startDate:'%y-%M-01',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true})"/>
					<input type="hidden" name="appId" value="${appDetail.appDesc.appId}">
					<input type="hidden" name="tabTag" value="app_command_analysis">
					<input type="hidden" id="firstCommand" name="firstCommand" value="${firstCommand}">
					<label>&nbsp;<input type="submit" class="btn-4" value="查询"/></label>
			</div>
		</div>
		<div class="row">
				<c:set var="needSelect" value="0"></c:set>
				&nbsp;&nbsp;Top5命令:
				<c:forEach items="${allCommands}" var="item" varStatus="stat">
					<c:choose>
						<c:when test="${stat.index < 5}">
								<input type="radio" name="optionsRadios" value="${item.commandName}" 
								<c:if test="${firstCommand == item.commandName}">checked="checked"</c:if>
								 onchange="changeCommandChart(this.value)" />
								${item.commandName}
						</c:when>
						<c:otherwise>
							<c:set var="needSelect" value="1"></c:set>
						</c:otherwise>
					</c:choose>
				</c:forEach>
				<c:if test="${needSelect == 1}">
					&nbsp;&nbsp;&nbsp;其余命令:
					<select name="optionsRadios" onchange="changeCommandChart(this.value)">
						<option>请选择</option>
						<c:forEach items="${allCommands}" var="item" varStatus="stat">
							<c:choose>
								<c:when test="${stat.index >= 5}">
									<label>
										<option value="${item.commandName}" <c:if test="${firstCommand == item.commandName}">selected</c:if>>
							         		${item.commandName}
							        	</option>
									</label>							
								</c:when>
							</c:choose>
						</c:forEach>
					</select>
				</c:if>
				
		</div>
	</form>
	<script type="text/javascript">
		var title = "<b>"+firstCommand+"命令</b>";
		if(betweenOneDay == 1){
			$(document).ready(
				function() {
					var options = getOption("containerSingleCommand", title, "次数");
					var commandsUrl = "/admin/app/getCommandStats.do?appId=" + appId+ "&commandName=" + firstCommand + chartParams;
					$.ajax({
						type : "get",
						url : commandsUrl,
						async : false,
						success : function(data) {
							var nameLegend = firstCommand + "命令趋势图(" + startDate + ")";
							var finalPoints = getSeriesPoints(data, nameLegend);
							options.series.push(finalPoints);
						}
					});
					
					//比较
					var commandsUrlCompare = "/admin/app/getCommandStats.do?appId=" + appId + "&commandName=" + firstCommand + chartParamsCompare + "&addDay=1";
					$.ajax({
						type : "get",
						url : commandsUrlCompare,
						async : false,
						success : function(data) {
							var nameLegend = firstCommand + "命令趋势图(" + yesterDate + ")";
							var finalPoints = getSeriesPoints(data, nameLegend);
							options.series.push(finalPoints);
						}
					});
					new Highcharts.Chart(options);
			 });
		}else{
			$(document).ready(
				function() {
					var options = getOption("containerSingleCommand", title, "次数");
					var commandsUrl = "/admin/app/getCommandStats.do?appId=" + appId + "&commandName=" + firstCommand + chartParams;
					$.ajax({
						type : "get",
						url : commandsUrl,
						async : false,
						success : function(data) {
							var nameLegend = firstCommand + "命令趋势图";
							var finalPoints = getSeriesPoints(data, nameLegend);
							options.series.push(finalPoints);
						}
					});
					new Highcharts.Chart(options);
			 });
		}
	</script>
	
	
	<div id="containerSingleCommand"
		style="min-width: 310px; height: 350px; margin: 0 auto"></div>

</div>

cachecloud-open-web/src/main/webapp/WEB-INF/jsp/app/appDemo.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="/WEB-INF/jsp/manage/commons/taglibs.jsp" %>
<div class="row">
    <br/>
    <div id="dependency" class="highlight">
        <pre class="prettyprint">
            <c:forEach var="line" items="${dependency}">
            ${line}<br/>
            </c:forEach>
        </pre>
    </div>

    <div id="code" class="highlight">
        <pre class="prettyprint">
        <c:forEach var="line" items="${code}">
            ${line}<br/>
        </c:forEach>
        </pre>
    </div>
    
    <c:if test="${springConfig != null}">
	    <div id="springConfig" class="highlight">
	        <pre class="prettyprint">
	        <c:forEach var="line" items="${springConfig}">
	            ${line}<br/>
	        </c:forEach>
	        </pre>
	    </div>
    </c:if>
    
</div>
<script>
    prettyPrint();
</script>

cachecloud-open-web/src/main/webapp/WEB-INF/jsp/app/appTopology.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="/WEB-INF/jsp/manage/commons/taglibs.jsp"%>

<div class="row">
    <div class="page-header">
        <h4>应用拓扑结构-${appDesc.type}-<a href="/admin/app/index.do?appId=${appDesc.appId}">${appDesc.name}</a></h4>
    </div>
    <div style="margin-top: 20px">
        <table class="table table-bordered table-striped table-hover">
            <thead>
            <tr>
                <td>ID</td>
                <td>实例</td>
                <td>实例状态</td>
                <td>内存使用</td>
                <td>对象数</td>
                <td>连接数</td>
                <td>命中率</td>
                <td>角色</td>
                <td>主实例ID</td>
            </tr>
            </thead>
            <tbody>
            <c:forEach var="instance" items="${instanceList}" varStatus="status">
            	<c:set var="instanceStatsMapKey" value="${instance.ip}:${instance.port}"></c:set>
                <tr>
                    <td><a href="/admin/instance/index.do?instanceId=${instance.id}" target="_blank">${instance.id}</a>
                    </td>
                    <td>${instance.ip}:${instance.port}</td>
                    <td>${instance.statusDesc}</td>
					<td>
                         <div class="progress margin-custom-bottom0">
                         	<c:choose>
                             	<c:when test="${(instanceStatsMap[instanceStatsMapKey]).memUsePercent >= 80}">
                               <div class="progress-bar progress-bar-danger"
                                    role="progressbar"
                                    aria-valuenow="${(instanceStatsMap[instanceStatsMapKey]).memUsePercent}"
                                    aria-valuemax="100"
                                    aria-valuemin="0"
                                    style="width: ${(instanceStatsMap[instanceStatsMapKey]).memUsePercent}%">
                                    
                               	<label style="color: #000000">
                                   <fmt:formatNumber value="${(instanceStatsMap[instanceStatsMapKey]).usedMemory / 1024 / 1024 / 1024}" pattern="0.00"/>G&nbsp;&nbsp;Used/<fmt:formatNumber value="${(instanceStatsMap[instanceStatsMapKey]).maxMemory / 1024 / 1024 / 1024}" pattern="0.00"/>G&nbsp;&nbsp;Total
                               	</label>
                                   </div>
                                 </c:when>
                                 <c:otherwise>
                                  <div class="progress-bar progress-bar-success"
                                       role="progressbar"
                                       aria-valuenow="${(instanceStatsMap[instanceStatsMapKey]).memUsePercent}"
                                       aria-valuemax="100"
                                       aria-valuemin="0"
                                       style="width: ${(instanceStatsMap[instanceStatsMapKey]).memUsePercent}%">
                                       
                                   	<label style="color: #000000">
                                   <fmt:formatNumber value="${(instanceStatsMap[instanceStatsMapKey]).usedMemory / 1024 / 1024 / 1024}" pattern="0.00"/>G&nbsp;&nbsp;Used/<fmt:formatNumber value="${(instanceStatsMap[instanceStatsMapKey]).maxMemory / 1024 / 1024 / 1024}" pattern="0.00"/>G&nbsp;&nbsp;Total
                               	</label>
                                   </div>
                                 </c:otherwise>
                            </c:choose>
                         </div>
                  </td>
                  <td>
                  ${(instanceStatsMap[instanceStatsMapKey]).currItems}
                  </td>
                  <td>${(instanceStatsMap[instanceStatsMapKey]).currConnections}</td>
                  <td>${(instanceStatsMap[instanceStatsMapKey]).hitPercent}</td>
                  <td>${instance.roleDesc}</td>
                  <c:choose>
                     <c:when test="${instance.masterInstanceId >0}">
                         <td>
                             <a href="/admin/instance/index.do?instanceId=${instance.masterInstanceId}" target="_blank">${instance.masterInstanceId}</a>
                         </td>
                     </c:when>
                     <c:otherwise>
                         <td></td>
                     </c:otherwise>
                 </c:choose>
                </tr>
            </c:forEach>
            </tbody>
        </table>
    </div>
</div>

cachecloud-open-web/src/main/webapp/WEB-INF/jsp/app/manageUser.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<div id="manageUser" class="modal fade" tabindex="-1" data-width="400">
	<div class="modal-dialog">
		<div class="modal-content">
		
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
				<h4 class="modal-title">添加用户</h4>
			</div>
			
			<form action="/user/add.do" method="post" class="form-horizontal form-bordered form-row-stripped">
				<div class="modal-body">
					<div class="row">
						<!-- 控件开始 -->
						<div class="col-md-12">
							<div class="form-body">
								<div class="form-group">
									<label class="control-label col-md-3">
										用户名:
									</label>
									<div class="col-md-5">
										<input type="text" name="name" id="user.name"
											value="${user.name}" placeholder="用户名"
											class="form-control" />
									</div>
								</div>
								
								<div class="form-group">
									<label class="control-label col-md-3">
										邮箱:
									</label>
									<div class="col-md-5">
										<input type="text" name="email" id="user.email"
											value="${user.email}" placeholder="邮箱"
											class="form-control" />
									</div>
								</div>
								
								<div class="form-group">
									<label class="control-label col-md-3">
										手机:
									</label>
									<div class="col-md-5">
										<input type="text" name="mobile" id="user.mobile"
											value="${user.mobile}" placeholder="手机"
											class="form-control" />
									</div>
								</div>
							</div>
						</div>
						<!-- 控件结束 -->
					</div>
				</div>
				
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn">Close</button>
					<button type="submit" class="btn red">Ok</button>
				</div>
			
			</form>
		</div>
	</div>
</div>